#Arithmatic Operators
a=int(input("Enter Value For a :"))
b=int(input("Enter Value For b :"))
print("="*50)
print("\tArithmatic Operators")
print("="*50)
# + -  *  /  //  **  %
print("Sum =({} and {}) :{}".format(a,b,a+b))
print("Sub =({} and {}) :{}".format(a,b,a-b))
print("Mul =({} and {}) :{}".format(a,b,a*b))
print("Div =({} and {}) :{}".format(a,b,a/b))
print("Rem =({} and {}) :{}".format(a,b,a%b))
print("Mod Div =({} and {}) :{}".format(a,b,a//b))
print("Exeponational =({} and {}) :{}".format(a,b,a*b))
print("="*50)