print("="*50)
print("A R I T H M A T I C  O P E R A T O R S ")
print("="*50)
a=float(input("Enter Value Of  a  :"))
b=float(input("Enter Value Of  b  :"))
print("Addition          : {} and {} = {}".format(a,b,a+b))
print("Subtraction       : {} and {} = {}".format(a,b,a-b))
print("Multiplication    : {} and {} = {}".format(a,b,a*b))
print("Division          : {} and {} = {}".format(a,b,a/b))
print("Modulo Division   : {} and {} = {}".format(a,b,a//b))
print("Remainder         : {} and {} = {}".format(a,b,a%b))
print("Exponanetiton     : {} and {} = {}".format(a,b,a*b))
print("="*50)