print("="*50)
print("R E L A T I O N A L  O P E R A T O R S ")
print("="*50)
a=float(input("Enter Value Of  a  :"))
b=float(input("Enter Value Of  b  :"))
print("Greater Than           : {} and {} = {}".format(a,b,a>b))
print("Less Than              : {} and {} = {}".format(a,b,a<b))
print("Equality               : {} and {} = {}".format(a,b,a==b))
print("Not Equal              : {} and {} = {}".format(a,b,a!=b))
print("Greater Than Equal     : {} and {} = {}".format(a,b,a>=b))
print("Less Than Equal        : {} and {} = {}".format(a,b,a<=b))
print("="*50)